# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: t4w4n3 - Blog
email: contact@antoine-salesse.fr
description: >- # this means to ignore newlines until "baseurl:"
  
  Bienvenue sur mon blog tech, je suis Antoine Salesse, ingénieur software de spécialité back-end et testing, aussi à l'aise sur en front-end + ops + product-ownership.
  Je bosse avec passion pour Younup et ses clients.
  Vous trouverez ici des articles autour de la JVM,
  et des outils de dev que je maitrise,
  ou que je découvre et tiens absolument à faire gagner en popularité.
  Certains sont publiés sur le blog de Younup.
baseurl: "/fr" # the subpath of your site, e.g. /blog
url: "https://t4w4n3.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  t4w4n3
linkedin_username: antoine-salesse

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
